## 注意不能使用MySQL太高版本，否则会连不上数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: root
    #schema: database/import.sql
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mapper/*.xml
debug: true
server:
  port: 8888
